# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Package Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean install
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .    
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/event-app-event-service:latest
        
    - name: Rancher Deploy
      uses: yantadeu/rancher-deploy-action@v0.0.3
      env:
        RANCHER_ACCESS_KEY: ${{ secrets.RANCHER_USERNAME }}
        RANCHER_SECRET_KEY: ${{ secrets.RANCHER_PASSWORD }}
        RANCHER_URL_API: 'https://rancher.alikhani.io/v3'
        SERVICE_NAME: 'event-service'
        DOCKER_IMAGE:  ${{ secrets.DOCKERHUB_USERNAME }}/event-app-event-service:latest
